include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/**.freezed.dart"
    - "**/**.config.dart"
    - "**/**.module.dart"
    - "**/**.gr.dart"
    - "**/**.gm.dart"
    - "**/**.freezed.dart"
    - "**/**.g.dart"
  errors:
    specify_nonobvious_property_types: ignore
    avoid_bool_literals_in_conditional_expressions: ignore
    one_member_abstracts: ignore
    cascade_invocations: ignore
    use_build_context_synchronously: ignore
    discarded_futures: ignore

linter:
  rules:
    public_member_api_docs: false
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
