name: form_gear_engine_sdk
description: "Flutter SDK for FormGear - A flexible, JSON-driven form generation framework for dynamic data collection with 30+ input control types, nested forms, GPS, photo capture, and complex validation capabilities."
version: 0.1.0
repository: https://github.com/IPDS-59/form_gear_flutter_sdk
homepage: https://github.com/bps-statistics/form-gear

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  alice_dio: ^1.0.7
  archive: ^4.0.7
  camera: ^0.11.2
  crypto: ^3.0.5
  dio: ^5.7.0
  encrypt: ^5.0.3
  equatable: ^2.0.7
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_inappwebview: ^6.1.5
  flutter_svg: ^2.0.16
  geolocator: ^14.0.2
  get_it: ^8.2.0
  http: ^1.2.2
  image_picker: ^1.2.0
  injectable: ^2.5.1
  json_annotation: ^4.9.0
  just_audio: ^0.10.5
  mobile_scanner: ^7.1.2
  mocktail: ^1.0.4
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  record: ^6.1.1
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  waveform_flutter: ^1.2.0

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1
  very_good_analysis: ^10.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets for debug-only bridge testing and JavaScript files
  assets:
    - assets/test/bridge_test.html
    - assets/js/android_bridge.js
    - assets/vendor/jquery-3.5.1.js
    - assets/logo/form-gear.svg
    # FASIH client default data assets (exact structure from FASIH)
    - assets/client/formgear/response.json
    - assets/client/formgear/media.json
    - assets/client/formgear/reference.json
#
# For details regarding assets in packages, see
# https://flutter.dev/to/asset-from-package
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/to/resolution-aware-images
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/to/font-from-package
