name: ✨ Feature Request
description: Suggest an idea or new feature for FormGear Engine SDK
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the documentation and roadmap
          required: true
        - label: This feature request is related to FormGear Engine SDK functionality
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A brief, clear summary of the feature you'd like to see
      placeholder: One-line summary of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        Example: I'm frustrated when [current behavior] because [reason]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        A clear and concise description of what you want to happen.
        How would this feature work? What would the API look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: What other approaches have you considered? Why would this solution be better?

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a developer, I want to... so that...
        2. When building forms with..., I need to...
        3. For FASIH integration, it would be helpful to...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: API Design (Optional)
      description: If you have ideas about the API design, describe them here
      render: dart
      placeholder: |
        // Example API usage
        FormGearSDK.newFeature(
          parameter1: 'value',
          onCallback: (result) {
            // Handle result
          },
        );

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Core SDK functionality
        - WebView integration
        - JavaScript bridge
        - Form engine support
        - FASIH integration
        - Developer experience
        - Documentation
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have, not urgent
        - Medium - Would improve workflow significantly
        - High - Important for project success
        - Critical - Blocking current development
      default: 1
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
      placeholder: |
        Any additional information, mockups, links to similar features in other libraries, etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contributing
      description: Would you like to contribute to implementing this feature?
      options:
        - label: I would like to work on implementing this feature
          required: false
        - label: I can help with testing this feature
          required: false
        - label: I can help with documentation for this feature
          required: false